### ISSUE TITLE
AccumulatingReducer (and all derivatives) call after_stream() twice.

### ISSUE THREAD

**Issue by dotdotdotpaul** [infochimps-labs/wukong#1]
AccumulatingReducer's stream() method calls super() and then calls after_stream.  However, since after_stream is called from Base's version of stream(), this causes after_stream to be called twice.  Since this is also the basis for the other Reducers, any reducer inheriting from AccumulatingReducer suffers the same problem.

**Comment by alienrobotwizard** [comment]
fixed, though the fact that the last call to finalize() takes place AFTER the after stream method is very misleading and should be addressed

**Comment by dotdotdotpaul** [comment]
Ah, looks like mrflip made some tweaks after you, and the current 1.5.1 version definitely looks like a cleaner organization.  Yay internets!
