### ISSUE TITLE
Connect to SQL database

### ISSUE THREAD

**Issue by ramanbedi1989** [infochimps-labs/wukong#17]
In 0.0.2 we had streamers and we could connect to database by requiring 'wukong/schema'.
Now in 3.0.1 is it possible to connect to sql and fetch data. I searched the internet but couldn't find any docs regarding sql connection in 3.0.1

**Comment by dhruvbansal** [comment]
There's not as much built-in database interaction in the Wukong 3.x series.  You may want to check out the [wukong-load](http://github.com/infochimps-labs/wukong-load) plugin which has does provide limited database interop for Wukong dataflows & processors.
