### ISSUE TITLE
Accessing files from HDFS

### ISSUE THREAD

**Issue by ramanbedi1989** [infochimps-labs/wukong#18]
Now I am stuck with a problem that our program uses yaml files for loading data. The program cannot read files from local file system while running in hadoop.
I can put my files into HDFS.
But is there a way in wukong-hadoop to read files from HDFS in ruby program?

**Comment by dhruvbansal** [comment]
One common approach is to use a deploy pack (
http://github.com/infochimps-labs/wukong-deploy) to hold all your Wukong
(or other code) AND your YAML configuration files.

You can either

1) place this deploy pack at the same location on all Hadoop workers
2) place this deploy pack on an NFS mount accessible to all Hadoop workers.

Both methods should ensure that your Hadoop map/reduce tasks have access to
the code (and config files) at runtime.

-dhruv

**Comment by ramanbedi1989** [comment]
Thanks your comment was really helpful. Thanks a ton.
