### ISSUE TITLE
Wukong-hadoop giving error with Rails

### ISSUE THREAD

**Issue by ramanbedi1989** [infochimps-labs/wukong#19]
I included wukong-hadoop as a gem in Gemfile.
Bundle install installs the gem properly without error.
Now when I try to run any rake task or rails console or rails server the following error:

/home/raman/.rvm/gems/ruby-1.9.3-p327@rails329/gems/gorillib-0.5.0/lib/gorillib/model/schema_magic.rb:25:in `field': undefined method`name' for #Gorillib::Model::Field:0xbb29cf0 (NoMethodError)

I can't get wukong to work with rails. I just want to include it so that I can run rake tasks from the rails app to interact with hadoop.
Please help.

**Comment by dhruvbansal** [comment]
Wukong wasn't written to interact with Rails in any particular way.  It
_was_ written to pay attention to a file `config/environment.rb` if such a
file exists relative to the path that it was invoked from.  In Rails, I
believe such a file _does_ exist, and perhaps is responsible for booting up
the entire Rails environment?  It's possible that Wukong is additionally
reading this file on bootup and something weird is happening.

Is it absolutely necessary for you to put your Wukong code and your Rails
app in the same code repository?  Why not create two separate repos, one
for your Rails application and one for your Wukong deploy pack?

**Comment by ramanbedi1989** [comment]
Thanks I also implemented it the same way.
