### ISSUE TITLE
Vayacondios

### ISSUE THREAD

**Issue by PseudoCorps** [infochimps-labs/wukong#21]
I'm not sure if this is platform specific or not, but every time I try to run wukong i get an error 

/wukong/processor.rb:16:in `class:Processor': uninitialized constant Vayacondios::Notifications (NameError)

**Comment by dhruvbansal** [comment]
Please ensure you're using the "leslie" branch of Wukong...unfortunately we are rather behind in keeping "master" usable.

**Comment by PseudoCorps** [comment]
Thank you soo much for the quick reply. So I cloned the leslie branch, but I'm still having trouble running the examples. 

The error is now:
/home/snow/.rbenv/versions/2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require': cannot load such file -- gorillib/model/indexable (LoadError)

Are there installation steps to getting the examples working?

**Comment by joshbronson** [comment]
Hope the steps we've outlined in https://github.com/infochimps-labs/wukong/issues/23 have helped you. Please re-open if not!
