### ISSUE TITLE
Still Unable to run

### ISSUE THREAD

**Issue by PseudoCorps** [infochimps-labs/wukong#23]
Hi, I'm not sure If I'm missing something, but I've been trying for quite some time to get wukong to work. I even asked about it once before and was instructed to use the leslie branch, but I got the same errors. Now I received the update about the master branch update and I was hoping that it would resolve the problem, but it doesn’t seem to have fixed it. I've tried changing ruby versions, and running every example, but I cant seem to get any of them to work for one reason or another. Most of the time I get dependency errors. 
Is there a very specific version of ruby we need to run?
Is the package not compatible for some reason with rbenv?
Is the package for some reason not compatible with linux?
Am I not installing the gem properly?
Are the examples not supposed to work?

Sorry for so many questions, it's just last time I only got one response. I would just like to know if the package will ever be a viable option or not.
Thanks

**Comment by PseudoCorps** [comment]
These are the types of errors I'm getting

![screenshot from 2014-03-05 22 08 48](https://f.cloud.github.com/assets/2850172/2341511/39a5597e-a4dd-11e3-87d8-19f971721cd1.png)

![screenshot from 2014-03-05 22 11 26](https://f.cloud.github.com/assets/2850172/2341512/3d2fac66-a4dd-11e3-903b-5fc9678aa47e.png)

**Comment by joshbronson** [comment]
We're about to merge 'leslie' into 'master' branch. Until then, gem installing will bring in 'master' branch. Sorry for the trouble. We typically run with 1.9.x, but I'd be surprised if later versions cause trouble. I use rbenv on my Mac as well as the natively installed Ruby binaries on Ubuntu. I have never had any compatibility issues.

The easiest way to get the examples working is to use them with bundler and the wu-local driver:

```
$ git clone -b leslie git@github.com:infochimps-labs/wukong.git
$ cd wukong
$ bundle install
$ bundle exec wu-local examples/string_reverser.rb
```
